// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package brewery_model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_04713fa1218e5667, []int{0}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type TemperatureSensor struct {
	Serial               string    `protobuf:"bytes,1,opt,name=serial,proto3" json:"serial,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TemperatureSensor) Reset()         { *m = TemperatureSensor{} }
func (m *TemperatureSensor) String() string { return proto.CompactTextString(m) }
func (*TemperatureSensor) ProtoMessage()    {}
func (*TemperatureSensor) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_04713fa1218e5667, []int{1}
}
func (m *TemperatureSensor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemperatureSensor.Unmarshal(m, b)
}
func (m *TemperatureSensor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemperatureSensor.Marshal(b, m, deterministic)
}
func (dst *TemperatureSensor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemperatureSensor.Merge(dst, src)
}
func (m *TemperatureSensor) XXX_Size() int {
	return xxx_messageInfo_TemperatureSensor.Size(m)
}
func (m *TemperatureSensor) XXX_DiscardUnknown() {
	xxx_messageInfo_TemperatureSensor.DiscardUnknown(m)
}

var xxx_messageInfo_TemperatureSensor proto.InternalMessageInfo

func (m *TemperatureSensor) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *TemperatureSensor) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *TemperatureSensor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SSR struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SSR) Reset()         { *m = SSR{} }
func (m *SSR) String() string { return proto.CompactTextString(m) }
func (*SSR) ProtoMessage()    {}
func (*SSR) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_04713fa1218e5667, []int{2}
}
func (m *SSR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSR.Unmarshal(m, b)
}
func (m *SSR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSR.Marshal(b, m, deterministic)
}
func (dst *SSR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSR.Merge(dst, src)
}
func (m *SSR) XXX_Size() int {
	return xxx_messageInfo_SSR.Size(m)
}
func (m *SSR) XXX_DiscardUnknown() {
	xxx_messageInfo_SSR.DiscardUnknown(m)
}

var xxx_messageInfo_SSR proto.InternalMessageInfo

func (m *SSR) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *SSR) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BreweryConfig struct {
	Mash                 *TemperatureSensor `protobuf:"bytes,1,opt,name=mash,proto3" json:"mash,omitempty"`
	Boil                 *TemperatureSensor `protobuf:"bytes,2,opt,name=boil,proto3" json:"boil,omitempty"`
	Herms                *TemperatureSensor `protobuf:"bytes,3,opt,name=herms,proto3" json:"herms,omitempty"`
	BoilHeater           *SSR               `protobuf:"bytes,4,opt,name=boil_heater,json=boilHeater,proto3" json:"boil_heater,omitempty"`
	Scheme               *ControlScheme     `protobuf:"bytes,5,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BreweryConfig) Reset()         { *m = BreweryConfig{} }
func (m *BreweryConfig) String() string { return proto.CompactTextString(m) }
func (*BreweryConfig) ProtoMessage()    {}
func (*BreweryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_04713fa1218e5667, []int{3}
}
func (m *BreweryConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreweryConfig.Unmarshal(m, b)
}
func (m *BreweryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreweryConfig.Marshal(b, m, deterministic)
}
func (dst *BreweryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreweryConfig.Merge(dst, src)
}
func (m *BreweryConfig) XXX_Size() int {
	return xxx_messageInfo_BreweryConfig.Size(m)
}
func (m *BreweryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BreweryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BreweryConfig proto.InternalMessageInfo

func (m *BreweryConfig) GetMash() *TemperatureSensor {
	if m != nil {
		return m.Mash
	}
	return nil
}

func (m *BreweryConfig) GetBoil() *TemperatureSensor {
	if m != nil {
		return m.Boil
	}
	return nil
}

func (m *BreweryConfig) GetHerms() *TemperatureSensor {
	if m != nil {
		return m.Herms
	}
	return nil
}

func (m *BreweryConfig) GetBoilHeater() *SSR {
	if m != nil {
		return m.BoilHeater
	}
	return nil
}

func (m *BreweryConfig) GetScheme() *ControlScheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

type ControlScheme struct {
	// Types that are valid to be assigned to Scheme:
	//	*ControlScheme_Boil_
	//	*ControlScheme_Mash_
	//	*ControlScheme_Power_
	Scheme               isControlScheme_Scheme `protobuf_oneof:"scheme"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ControlScheme) Reset()         { *m = ControlScheme{} }
func (m *ControlScheme) String() string { return proto.CompactTextString(m) }
func (*ControlScheme) ProtoMessage()    {}
func (*ControlScheme) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_04713fa1218e5667, []int{4}
}
func (m *ControlScheme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlScheme.Unmarshal(m, b)
}
func (m *ControlScheme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlScheme.Marshal(b, m, deterministic)
}
func (dst *ControlScheme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlScheme.Merge(dst, src)
}
func (m *ControlScheme) XXX_Size() int {
	return xxx_messageInfo_ControlScheme.Size(m)
}
func (m *ControlScheme) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlScheme.DiscardUnknown(m)
}

var xxx_messageInfo_ControlScheme proto.InternalMessageInfo

type isControlScheme_Scheme interface {
	isControlScheme_Scheme()
}

type ControlScheme_Boil_ struct {
	Boil *ControlScheme_Boil `protobuf:"bytes,1,opt,name=boil,proto3,oneof"`
}

type ControlScheme_Mash_ struct {
	Mash *ControlScheme_Mash `protobuf:"bytes,2,opt,name=mash,proto3,oneof"`
}

type ControlScheme_Power_ struct {
	Power *ControlScheme_Power `protobuf:"bytes,3,opt,name=power,proto3,oneof"`
}

func (*ControlScheme_Boil_) isControlScheme_Scheme() {}

func (*ControlScheme_Mash_) isControlScheme_Scheme() {}

func (*ControlScheme_Power_) isControlScheme_Scheme() {}

func (m *ControlScheme) GetScheme() isControlScheme_Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

func (m *ControlScheme) GetBoil() *ControlScheme_Boil {
	if x, ok := m.GetScheme().(*ControlScheme_Boil_); ok {
		return x.Boil
	}
	return nil
}

func (m *ControlScheme) GetMash() *ControlScheme_Mash {
	if x, ok := m.GetScheme().(*ControlScheme_Mash_); ok {
		return x.Mash
	}
	return nil
}

func (m *ControlScheme) GetPower() *ControlScheme_Power {
	if x, ok := m.GetScheme().(*ControlScheme_Power_); ok {
		return x.Power
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ControlScheme) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ControlScheme_OneofMarshaler, _ControlScheme_OneofUnmarshaler, _ControlScheme_OneofSizer, []interface{}{
		(*ControlScheme_Boil_)(nil),
		(*ControlScheme_Mash_)(nil),
		(*ControlScheme_Power_)(nil),
	}
}

func _ControlScheme_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ControlScheme)
	// scheme
	switch x := m.Scheme.(type) {
	case *ControlScheme_Boil_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Boil); err != nil {
			return err
		}
	case *ControlScheme_Mash_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Mash); err != nil {
			return err
		}
	case *ControlScheme_Power_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Power); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ControlScheme.Scheme has unexpected type %T", x)
	}
	return nil
}

func _ControlScheme_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ControlScheme)
	switch tag {
	case 1: // scheme.boil
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ControlScheme_Boil)
		err := b.DecodeMessage(msg)
		m.Scheme = &ControlScheme_Boil_{msg}
		return true, err
	case 2: // scheme.mash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ControlScheme_Mash)
		err := b.DecodeMessage(msg)
		m.Scheme = &ControlScheme_Mash_{msg}
		return true, err
	case 3: // scheme.power
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ControlScheme_Power)
		err := b.DecodeMessage(msg)
		m.Scheme = &ControlScheme_Power_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ControlScheme_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ControlScheme)
	// scheme
	switch x := m.Scheme.(type) {
	case *ControlScheme_Boil_:
		s := proto.Size(x.Boil)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ControlScheme_Mash_:
		s := proto.Size(x.Mash)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ControlScheme_Power_:
		s := proto.Size(x.Power)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ControlScheme_Boil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlScheme_Boil) Reset()         { *m = ControlScheme_Boil{} }
func (m *ControlScheme_Boil) String() string { return proto.CompactTextString(m) }
func (*ControlScheme_Boil) ProtoMessage()    {}
func (*ControlScheme_Boil) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_04713fa1218e5667, []int{4, 0}
}
func (m *ControlScheme_Boil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlScheme_Boil.Unmarshal(m, b)
}
func (m *ControlScheme_Boil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlScheme_Boil.Marshal(b, m, deterministic)
}
func (dst *ControlScheme_Boil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlScheme_Boil.Merge(dst, src)
}
func (m *ControlScheme_Boil) XXX_Size() int {
	return xxx_messageInfo_ControlScheme_Boil.Size(m)
}
func (m *ControlScheme_Boil) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlScheme_Boil.DiscardUnknown(m)
}

var xxx_messageInfo_ControlScheme_Boil proto.InternalMessageInfo

type ControlScheme_Mash struct {
	MashMinTemp          float64  `protobuf:"fixed64,1,opt,name=mash_min_temp,json=mashMinTemp,proto3" json:"mash_min_temp,omitempty"`
	MashMaxTemp          float64  `protobuf:"fixed64,2,opt,name=mash_max_temp,json=mashMaxTemp,proto3" json:"mash_max_temp,omitempty"`
	HermsMinTemp         float64  `protobuf:"fixed64,3,opt,name=herms_min_temp,json=hermsMinTemp,proto3" json:"herms_min_temp,omitempty"`
	HermsMaxTemp         float64  `protobuf:"fixed64,4,opt,name=herms_max_temp,json=hermsMaxTemp,proto3" json:"herms_max_temp,omitempty"`
	BoilMinTemp          float64  `protobuf:"fixed64,5,opt,name=boil_min_temp,json=boilMinTemp,proto3" json:"boil_min_temp,omitempty"`
	BoilMaxTemp          float64  `protobuf:"fixed64,6,opt,name=boil_max_temp,json=boilMaxTemp,proto3" json:"boil_max_temp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlScheme_Mash) Reset()         { *m = ControlScheme_Mash{} }
func (m *ControlScheme_Mash) String() string { return proto.CompactTextString(m) }
func (*ControlScheme_Mash) ProtoMessage()    {}
func (*ControlScheme_Mash) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_04713fa1218e5667, []int{4, 1}
}
func (m *ControlScheme_Mash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlScheme_Mash.Unmarshal(m, b)
}
func (m *ControlScheme_Mash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlScheme_Mash.Marshal(b, m, deterministic)
}
func (dst *ControlScheme_Mash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlScheme_Mash.Merge(dst, src)
}
func (m *ControlScheme_Mash) XXX_Size() int {
	return xxx_messageInfo_ControlScheme_Mash.Size(m)
}
func (m *ControlScheme_Mash) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlScheme_Mash.DiscardUnknown(m)
}

var xxx_messageInfo_ControlScheme_Mash proto.InternalMessageInfo

func (m *ControlScheme_Mash) GetMashMinTemp() float64 {
	if m != nil {
		return m.MashMinTemp
	}
	return 0
}

func (m *ControlScheme_Mash) GetMashMaxTemp() float64 {
	if m != nil {
		return m.MashMaxTemp
	}
	return 0
}

func (m *ControlScheme_Mash) GetHermsMinTemp() float64 {
	if m != nil {
		return m.HermsMinTemp
	}
	return 0
}

func (m *ControlScheme_Mash) GetHermsMaxTemp() float64 {
	if m != nil {
		return m.HermsMaxTemp
	}
	return 0
}

func (m *ControlScheme_Mash) GetBoilMinTemp() float64 {
	if m != nil {
		return m.BoilMinTemp
	}
	return 0
}

func (m *ControlScheme_Mash) GetBoilMaxTemp() float64 {
	if m != nil {
		return m.BoilMaxTemp
	}
	return 0
}

type ControlScheme_Power struct {
	PowerLevel           float64  `protobuf:"fixed64,1,opt,name=power_level,json=powerLevel,proto3" json:"power_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlScheme_Power) Reset()         { *m = ControlScheme_Power{} }
func (m *ControlScheme_Power) String() string { return proto.CompactTextString(m) }
func (*ControlScheme_Power) ProtoMessage()    {}
func (*ControlScheme_Power) Descriptor() ([]byte, []int) {
	return fileDescriptor_config_04713fa1218e5667, []int{4, 2}
}
func (m *ControlScheme_Power) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlScheme_Power.Unmarshal(m, b)
}
func (m *ControlScheme_Power) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlScheme_Power.Marshal(b, m, deterministic)
}
func (dst *ControlScheme_Power) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlScheme_Power.Merge(dst, src)
}
func (m *ControlScheme_Power) XXX_Size() int {
	return xxx_messageInfo_ControlScheme_Power.Size(m)
}
func (m *ControlScheme_Power) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlScheme_Power.DiscardUnknown(m)
}

var xxx_messageInfo_ControlScheme_Power proto.InternalMessageInfo

func (m *ControlScheme_Power) GetPowerLevel() float64 {
	if m != nil {
		return m.PowerLevel
	}
	return 0
}

func init() {
	proto.RegisterType((*Location)(nil), "brewery.model.Location")
	proto.RegisterType((*TemperatureSensor)(nil), "brewery.model.TemperatureSensor")
	proto.RegisterType((*SSR)(nil), "brewery.model.SSR")
	proto.RegisterType((*BreweryConfig)(nil), "brewery.model.BreweryConfig")
	proto.RegisterType((*ControlScheme)(nil), "brewery.model.ControlScheme")
	proto.RegisterType((*ControlScheme_Boil)(nil), "brewery.model.ControlScheme.Boil")
	proto.RegisterType((*ControlScheme_Mash)(nil), "brewery.model.ControlScheme.Mash")
	proto.RegisterType((*ControlScheme_Power)(nil), "brewery.model.ControlScheme.Power")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_config_04713fa1218e5667) }

var fileDescriptor_config_04713fa1218e5667 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x6b, 0xc7, 0xb6, 0xc2, 0xa4, 0x46, 0x62, 0x0f, 0x60, 0x45, 0x08, 0x82, 0xc5, 0x21,
	0x27, 0x1f, 0x48, 0x45, 0x25, 0x8e, 0xe9, 0xa5, 0x87, 0x16, 0xa1, 0x35, 0xf7, 0x68, 0x13, 0x06,
	0x6c, 0xc9, 0xf6, 0x5a, 0x6b, 0x43, 0xcb, 0xcb, 0xf0, 0x68, 0x1c, 0x78, 0x12, 0x34, 0xb3, 0xeb,
	0xc6, 0x09, 0x52, 0x15, 0x6e, 0xce, 0xe6, 0xfb, 0xbf, 0xf1, 0x3f, 0x9b, 0xc0, 0xf9, 0x4e, 0x37,
	0x5f, 0xcb, 0x6f, 0x59, 0x6b, 0x74, 0xaf, 0x45, 0xbc, 0x35, 0x78, 0x87, 0xe6, 0x67, 0x56, 0xeb,
	0x2f, 0x58, 0xa5, 0xaf, 0x60, 0x7a, 0xa3, 0x77, 0xaa, 0x2f, 0x75, 0x23, 0x04, 0x04, 0xad, 0x36,
	0x7d, 0xe2, 0x2d, 0xbc, 0xe5, 0x13, 0xc9, 0xcf, 0x69, 0x0f, 0xcf, 0x3e, 0x63, 0xdd, 0xa2, 0x51,
	0xfd, 0x77, 0x83, 0x39, 0x36, 0x9d, 0x36, 0xe2, 0x39, 0x44, 0x1d, 0x9a, 0x52, 0x55, 0x0e, 0x75,
	0x9f, 0xc4, 0x0a, 0xa6, 0x95, 0x93, 0x25, 0xfe, 0xc2, 0x5b, 0xce, 0xde, 0xbd, 0xc8, 0x0e, 0xc6,
	0x65, 0xc3, 0x2c, 0xf9, 0x00, 0xd2, 0xd4, 0x46, 0xd5, 0x98, 0x4c, 0xec, 0x54, 0x7a, 0x4e, 0x3f,
	0xc2, 0x24, 0xcf, 0xe5, 0x81, 0xcf, 0xfb, 0x5f, 0x9f, 0x3f, 0xf2, 0xfd, 0xf2, 0x21, 0x5e, 0xdb,
	0xe0, 0x15, 0x2f, 0x43, 0x5c, 0x40, 0x50, 0xab, 0xae, 0x70, 0xda, 0xc5, 0x91, 0xf6, 0x9f, 0xca,
	0x92, 0x69, 0x4a, 0x6d, 0x75, 0x59, 0xb9, 0x72, 0x27, 0xa4, 0x88, 0x16, 0xef, 0x21, 0x2c, 0xd0,
	0xd4, 0x1d, 0x57, 0x3c, 0x25, 0x66, 0x71, 0xb1, 0x82, 0x19, 0xe5, 0x37, 0x05, 0xaa, 0x1e, 0x4d,
	0x12, 0x70, 0x5a, 0x1c, 0xa5, 0xf3, 0x5c, 0x4a, 0x20, 0xec, 0x9a, 0x29, 0x71, 0x01, 0x51, 0xb7,
	0x2b, 0xb0, 0xc6, 0x24, 0x64, 0xfe, 0xe5, 0x11, 0x7f, 0xa5, 0x9b, 0xde, 0xe8, 0x2a, 0x67, 0x46,
	0x3a, 0x36, 0xfd, 0x3d, 0x81, 0xf8, 0xe0, 0x1b, 0x71, 0xe9, 0xaa, 0xda, 0x05, 0xbd, 0x79, 0xcc,
	0x92, 0xad, 0x69, 0xfc, 0x99, 0x6b, 0x7b, 0xe9, 0x36, 0xeb, 0x9f, 0x10, 0xbc, 0x55, 0x5d, 0x41,
	0x41, 0x5e, 0xee, 0x07, 0x08, 0x5b, 0x7d, 0x87, 0xc6, 0xad, 0x29, 0x7d, 0x34, 0xf9, 0x89, 0xc8,
	0xeb, 0x33, 0x69, 0x23, 0xf3, 0x08, 0x02, 0x7a, 0x89, 0xf9, 0x1f, 0x0f, 0x02, 0x92, 0x8a, 0x14,
	0x62, 0x92, 0x6e, 0xea, 0xb2, 0xd9, 0xf4, 0x58, 0xb7, 0xdc, 0xc3, 0x93, 0x33, 0x3a, 0xbc, 0x2d,
	0x1b, 0xda, 0xf9, 0x9e, 0x51, 0xf7, 0x96, 0xf1, 0x47, 0x8c, 0xba, 0x67, 0xe6, 0x2d, 0x3c, 0xe5,
	0xcb, 0xd8, 0x8b, 0x26, 0x0c, 0x9d, 0xf3, 0xe9, 0x60, 0xda, 0x53, 0x83, 0x2a, 0x18, 0x53, 0xce,
	0x95, 0x42, 0xcc, 0xf7, 0xf9, 0xa0, 0x0a, 0xed, 0x3c, 0x3a, 0x1c, 0xbd, 0x93, 0x65, 0x06, 0x51,
	0x34, 0x62, 0xac, 0x67, 0xbe, 0x84, 0x90, 0xeb, 0x8b, 0xd7, 0x30, 0xe3, 0xfa, 0x9b, 0x0a, 0x7f,
	0x60, 0xe5, 0x2a, 0x02, 0x1f, 0xdd, 0xd0, 0xc9, 0x7a, 0x3a, 0xfc, 0x18, 0xb6, 0x11, 0xff, 0xfb,
	0x57, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xca, 0xbd, 0x3f, 0x47, 0x0d, 0x04, 0x00, 0x00,
}
