// Code generated by protoc-gen-go. DO NOT EDIT.
// source: position.proto

package deltav_model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Vector3 is a 3D vector. Double is used as compared to float
// despite being 30% slower because the Math library uses Doubles.
type Vector3 struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=Z,proto3" json:"Z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector3) Reset()         { *m = Vector3{} }
func (m *Vector3) String() string { return proto.CompactTextString(m) }
func (*Vector3) ProtoMessage()    {}
func (*Vector3) Descriptor() ([]byte, []int) {
	return fileDescriptor_56e266f1a28a7893, []int{0}
}

func (m *Vector3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector3.Unmarshal(m, b)
}
func (m *Vector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector3.Marshal(b, m, deterministic)
}
func (m *Vector3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector3.Merge(m, src)
}
func (m *Vector3) XXX_Size() int {
	return xxx_messageInfo_Vector3.Size(m)
}
func (m *Vector3) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector3.DiscardUnknown(m)
}

var xxx_messageInfo_Vector3 proto.InternalMessageInfo

func (m *Vector3) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector3) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector3) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

// Position is a Vector3 spacial position combined with time.
type Position struct {
	Position             *Vector3 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	T                    int64    `protobuf:"varint,2,opt,name=T,proto3" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_56e266f1a28a7893, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetPosition() *Vector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Position) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

func init() {
	proto.RegisterType((*Vector3)(nil), "deltav.model.Vector3")
	proto.RegisterType((*Position)(nil), "deltav.model.Position")
}

func init() { proto.RegisterFile("position.proto", fileDescriptor_56e266f1a28a7893) }

var fileDescriptor_56e266f1a28a7893 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc8, 0x2f, 0xce,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0x49, 0xcd, 0x29,
	0x49, 0x2c, 0xd3, 0xcb, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x32, 0xe6, 0x62, 0x0f, 0x4b, 0x4d, 0x2e,
	0xc9, 0x2f, 0x32, 0x16, 0xe2, 0xe1, 0x62, 0x8c, 0x90, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0c, 0x62,
	0x8c, 0x00, 0xf1, 0x22, 0x25, 0x98, 0x20, 0xbc, 0x48, 0x10, 0x2f, 0x4a, 0x82, 0x19, 0xc2, 0x8b,
	0x52, 0xf2, 0xe6, 0xe2, 0x08, 0x80, 0x1a, 0x2a, 0x64, 0xc8, 0xc5, 0x01, 0xb3, 0x00, 0xac, 0x99,
	0xdb, 0x48, 0x54, 0x0f, 0xd9, 0x06, 0x3d, 0xa8, 0xf1, 0x41, 0x70, 0x65, 0x20, 0xc3, 0x42, 0xc0,
	0x46, 0x33, 0x07, 0x31, 0x86, 0x24, 0xb1, 0x81, 0x9d, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x7e, 0xae, 0xb2, 0x40, 0xa8, 0x00, 0x00, 0x00,
}
