// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reactor.proto

package deltav_model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReactorOutput_Type int32

const (
	ReactorOutput_UNKNOWN        ReactorOutput_Type = 0
	ReactorOutput_ENERGY_TJOULES ReactorOutput_Type = 1
	ReactorOutput_HEAT_TJOULES   ReactorOutput_Type = 2
	ReactorOutput_GAMMA_TJOULES  ReactorOutput_Type = 3
)

var ReactorOutput_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "ENERGY_TJOULES",
	2: "HEAT_TJOULES",
	3: "GAMMA_TJOULES",
}

var ReactorOutput_Type_value = map[string]int32{
	"UNKNOWN":        0,
	"ENERGY_TJOULES": 1,
	"HEAT_TJOULES":   2,
	"GAMMA_TJOULES":  3,
}

func (x ReactorOutput_Type) String() string {
	return proto.EnumName(ReactorOutput_Type_name, int32(x))
}

func (ReactorOutput_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a9d77bb3db9aa96, []int{1, 0}
}

type ReactRequest struct {
	DesiredEnergyTeraJoules float64  `protobuf:"fixed64,1,opt,name=desiredEnergyTeraJoules,proto3" json:"desiredEnergyTeraJoules,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ReactRequest) Reset()         { *m = ReactRequest{} }
func (m *ReactRequest) String() string { return proto.CompactTextString(m) }
func (*ReactRequest) ProtoMessage()    {}
func (*ReactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9d77bb3db9aa96, []int{0}
}

func (m *ReactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReactRequest.Unmarshal(m, b)
}
func (m *ReactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReactRequest.Marshal(b, m, deterministic)
}
func (m *ReactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReactRequest.Merge(m, src)
}
func (m *ReactRequest) XXX_Size() int {
	return xxx_messageInfo_ReactRequest.Size(m)
}
func (m *ReactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReactRequest proto.InternalMessageInfo

func (m *ReactRequest) GetDesiredEnergyTeraJoules() float64 {
	if m != nil {
		return m.DesiredEnergyTeraJoules
	}
	return 0
}

type ReactorOutput struct {
	Type                 ReactorOutput_Type `protobuf:"varint,1,opt,name=type,proto3,enum=deltav.model.ReactorOutput_Type" json:"type,omitempty"`
	Amount               float64            `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReactorOutput) Reset()         { *m = ReactorOutput{} }
func (m *ReactorOutput) String() string { return proto.CompactTextString(m) }
func (*ReactorOutput) ProtoMessage()    {}
func (*ReactorOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9d77bb3db9aa96, []int{1}
}

func (m *ReactorOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReactorOutput.Unmarshal(m, b)
}
func (m *ReactorOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReactorOutput.Marshal(b, m, deterministic)
}
func (m *ReactorOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReactorOutput.Merge(m, src)
}
func (m *ReactorOutput) XXX_Size() int {
	return xxx_messageInfo_ReactorOutput.Size(m)
}
func (m *ReactorOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ReactorOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ReactorOutput proto.InternalMessageInfo

func (m *ReactorOutput) GetType() ReactorOutput_Type {
	if m != nil {
		return m.Type
	}
	return ReactorOutput_UNKNOWN
}

func (m *ReactorOutput) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReactResponse struct {
	Outputs              []*ReactorOutput `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReactResponse) Reset()         { *m = ReactResponse{} }
func (m *ReactResponse) String() string { return proto.CompactTextString(m) }
func (*ReactResponse) ProtoMessage()    {}
func (*ReactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a9d77bb3db9aa96, []int{2}
}

func (m *ReactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReactResponse.Unmarshal(m, b)
}
func (m *ReactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReactResponse.Marshal(b, m, deterministic)
}
func (m *ReactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReactResponse.Merge(m, src)
}
func (m *ReactResponse) XXX_Size() int {
	return xxx_messageInfo_ReactResponse.Size(m)
}
func (m *ReactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReactResponse proto.InternalMessageInfo

func (m *ReactResponse) GetOutputs() []*ReactorOutput {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func init() {
	proto.RegisterEnum("deltav.model.ReactorOutput_Type", ReactorOutput_Type_name, ReactorOutput_Type_value)
	proto.RegisterType((*ReactRequest)(nil), "deltav.model.ReactRequest")
	proto.RegisterType((*ReactorOutput)(nil), "deltav.model.ReactorOutput")
	proto.RegisterType((*ReactResponse)(nil), "deltav.model.ReactResponse")
}

func init() { proto.RegisterFile("reactor.proto", fileDescriptor_2a9d77bb3db9aa96) }

var fileDescriptor_2a9d77bb3db9aa96 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0xb6, 0xb6, 0x30, 0x4d, 0x4a, 0x9c, 0x83, 0x96, 0xf6, 0x52, 0x72, 0xea, 0x29,
	0x87, 0xa8, 0xe0, 0x35, 0x42, 0x6c, 0xa9, 0x4d, 0x02, 0x6b, 0x8a, 0x78, 0x92, 0x68, 0x06, 0x11,
	0xd2, 0x6c, 0xdc, 0xec, 0x0a, 0xf9, 0x4d, 0xfe, 0x49, 0xc9, 0x36, 0x16, 0x85, 0xea, 0x6d, 0x77,
	0xde, 0x7b, 0xbc, 0x6f, 0x77, 0xc0, 0x12, 0x94, 0xbe, 0x48, 0x2e, 0xdc, 0x52, 0x70, 0xc9, 0xd1,
	0xcc, 0x28, 0x97, 0xe9, 0x87, 0xbb, 0xe3, 0x19, 0xe5, 0xce, 0x0a, 0x4c, 0xd6, 0xc8, 0x8c, 0xde,
	0x15, 0x55, 0x12, 0xaf, 0xe1, 0x3c, 0xa3, 0xea, 0x4d, 0x50, 0x16, 0x14, 0x24, 0x5e, 0xeb, 0x84,
	0x44, 0xba, 0xe6, 0x2a, 0xa7, 0x6a, 0x62, 0xcc, 0x8d, 0x85, 0xc1, 0xfe, 0x92, 0x9d, 0x4f, 0x03,
	0x2c, 0xb6, 0x6f, 0x8a, 0x95, 0x2c, 0x95, 0xc4, 0x4b, 0xe8, 0xcb, 0xba, 0x24, 0x1d, 0x1c, 0x7b,
	0x73, 0xf7, 0x67, 0xb1, 0xfb, 0xcb, 0xea, 0x26, 0x75, 0x49, 0x4c, 0xbb, 0xf1, 0x0c, 0x06, 0xe9,
	0x8e, 0xab, 0x42, 0x4e, 0xba, 0xba, 0xb0, 0xbd, 0x39, 0x1b, 0xe8, 0x37, 0x2e, 0x1c, 0xc1, 0x70,
	0x1b, 0xdd, 0x45, 0xf1, 0x43, 0x64, 0x77, 0x10, 0x61, 0x1c, 0x44, 0x01, 0x5b, 0x3e, 0x3e, 0x25,
	0xeb, 0x78, 0xbb, 0x09, 0xee, 0x6d, 0x03, 0x6d, 0x30, 0x57, 0x81, 0x9f, 0x1c, 0x26, 0x5d, 0x3c,
	0x05, 0x6b, 0xe9, 0x87, 0xa1, 0x7f, 0x18, 0xf5, 0x9c, 0xdb, 0x16, 0x96, 0x51, 0x55, 0xf2, 0xa2,
	0x22, 0xbc, 0x82, 0x21, 0xd7, 0x2c, 0xcd, 0x43, 0x7b, 0x8b, 0x91, 0x37, 0xfb, 0x87, 0x97, 0x7d,
	0x7b, 0xbd, 0x10, 0x86, 0xad, 0x82, 0x37, 0x70, 0xa2, 0x8f, 0x38, 0x3d, 0x92, 0x6c, 0xff, 0x77,
	0x3a, 0x3b, 0xaa, 0xed, 0x19, 0x9c, 0xce, 0xf3, 0x40, 0xef, 0xe8, 0xe2, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x69, 0x69, 0x62, 0x60, 0xb4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReactorClient is the client API for Reactor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReactorClient interface {
	React(ctx context.Context, in *ReactRequest, opts ...grpc.CallOption) (*ReactResponse, error)
}

type reactorClient struct {
	cc *grpc.ClientConn
}

func NewReactorClient(cc *grpc.ClientConn) ReactorClient {
	return &reactorClient{cc}
}

func (c *reactorClient) React(ctx context.Context, in *ReactRequest, opts ...grpc.CallOption) (*ReactResponse, error) {
	out := new(ReactResponse)
	err := c.cc.Invoke(ctx, "/deltav.model.Reactor/React", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReactorServer is the server API for Reactor service.
type ReactorServer interface {
	React(context.Context, *ReactRequest) (*ReactResponse, error)
}

func RegisterReactorServer(s *grpc.Server, srv ReactorServer) {
	s.RegisterService(&_Reactor_serviceDesc, srv)
}

func _Reactor_React_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactorServer).React(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deltav.model.Reactor/React",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactorServer).React(ctx, req.(*ReactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reactor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deltav.model.Reactor",
	HandlerType: (*ReactorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "React",
			Handler:    _Reactor_React_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reactor.proto",
}
