// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/golang001/brewery/model/gomodel (interfaces: SwitchClient,ThermometerClient)

// Package mock_gomodel is a generated GoMock package.
package mock_gomodel

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	gomodel "github.com/golang001/brewery/model/gomodel"
	grpc "google.golang.org/grpc"
	reflect "reflect"
)

// MockSwitchClient is a mock of SwitchClient interface
type MockSwitchClient struct {
	ctrl     *gomock.Controller
	recorder *MockSwitchClientMockRecorder
}

// MockSwitchClientMockRecorder is the mock recorder for MockSwitchClient
type MockSwitchClientMockRecorder struct {
	mock *MockSwitchClient
}

// NewMockSwitchClient creates a new mock instance
func NewMockSwitchClient(ctrl *gomock.Controller) *MockSwitchClient {
	mock := &MockSwitchClient{ctrl: ctrl}
	mock.recorder = &MockSwitchClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSwitchClient) EXPECT() *MockSwitchClientMockRecorder {
	return m.recorder
}

// Off mocks base method
func (m *MockSwitchClient) Off(arg0 context.Context, arg1 *gomodel.OffRequest, arg2 ...grpc.CallOption) (*gomodel.OffResponse, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Off", varargs...)
	ret0, _ := ret[0].(*gomodel.OffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Off indicates an expected call of Off
func (mr *MockSwitchClientMockRecorder) Off(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Off", reflect.TypeOf((*MockSwitchClient)(nil).Off), varargs...)
}

// On mocks base method
func (m *MockSwitchClient) On(arg0 context.Context, arg1 *gomodel.OnRequest, arg2 ...grpc.CallOption) (*gomodel.OnResponse, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "On", varargs...)
	ret0, _ := ret[0].(*gomodel.OnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// On indicates an expected call of On
func (mr *MockSwitchClientMockRecorder) On(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "On", reflect.TypeOf((*MockSwitchClient)(nil).On), varargs...)
}

// MockThermometerClient is a mock of ThermometerClient interface
type MockThermometerClient struct {
	ctrl     *gomock.Controller
	recorder *MockThermometerClientMockRecorder
}

// MockThermometerClientMockRecorder is the mock recorder for MockThermometerClient
type MockThermometerClientMockRecorder struct {
	mock *MockThermometerClient
}

// NewMockThermometerClient creates a new mock instance
func NewMockThermometerClient(ctrl *gomock.Controller) *MockThermometerClient {
	mock := &MockThermometerClient{ctrl: ctrl}
	mock.recorder = &MockThermometerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockThermometerClient) EXPECT() *MockThermometerClientMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockThermometerClient) Get(arg0 context.Context, arg1 *gomodel.GetRequest, arg2 ...grpc.CallOption) (*gomodel.GetResponse, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*gomodel.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockThermometerClientMockRecorder) Get(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockThermometerClient)(nil).Get), varargs...)
}
