// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worldmodel.proto

package deltav_protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	Position             *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a139271552183648, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type RegisterResponse struct {
	Effect               string   `protobuf:"bytes,1,opt,name=effect,proto3" json:"effect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a139271552183648, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

type DetectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectRequest) Reset()         { *m = DetectRequest{} }
func (m *DetectRequest) String() string { return proto.CompactTextString(m) }
func (*DetectRequest) ProtoMessage()    {}
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a139271552183648, []int{2}
}

func (m *DetectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectRequest.Unmarshal(m, b)
}
func (m *DetectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectRequest.Marshal(b, m, deterministic)
}
func (m *DetectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectRequest.Merge(m, src)
}
func (m *DetectRequest) XXX_Size() int {
	return xxx_messageInfo_DetectRequest.Size(m)
}
func (m *DetectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetectRequest proto.InternalMessageInfo

type DetectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectResponse) Reset()         { *m = DetectResponse{} }
func (m *DetectResponse) String() string { return proto.CompactTextString(m) }
func (*DetectResponse) ProtoMessage()    {}
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a139271552183648, []int{3}
}

func (m *DetectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectResponse.Unmarshal(m, b)
}
func (m *DetectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectResponse.Marshal(b, m, deterministic)
}
func (m *DetectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectResponse.Merge(m, src)
}
func (m *DetectResponse) XXX_Size() int {
	return xxx_messageInfo_DetectResponse.Size(m)
}
func (m *DetectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetectResponse proto.InternalMessageInfo

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a139271552183648, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type GetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a139271552183648, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "deltav.protos.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "deltav.protos.RegisterResponse")
	proto.RegisterType((*DetectRequest)(nil), "deltav.protos.DetectRequest")
	proto.RegisterType((*DetectResponse)(nil), "deltav.protos.DetectResponse")
	proto.RegisterType((*GetRequest)(nil), "deltav.protos.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "deltav.protos.GetResponse")
}

func init() { proto.RegisterFile("worldmodel.proto", fileDescriptor_a139271552183648) }

var fileDescriptor_a139271552183648 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x89, 0x90, 0xa2, 0x72, 0x25, 0x6d, 0x74, 0x03, 0x7f, 0x2c, 0xfe, 0xc9, 0x13, 0x62,
	0xc8, 0xd0, 0xee, 0x4c, 0x88, 0x4c, 0x95, 0x90, 0x17, 0x66, 0x68, 0xae, 0x28, 0x52, 0xa8, 0x43,
	0x7c, 0xc0, 0x17, 0xe6, 0x83, 0xa0, 0xc4, 0x76, 0xa2, 0x58, 0xcd, 0x78, 0xf7, 0x7b, 0xf7, 0xee,
	0x3d, 0x48, 0x7f, 0x75, 0x53, 0x15, 0x9f, 0xba, 0xa0, 0x2a, 0xab, 0x1b, 0xcd, 0x1a, 0x93, 0x82,
	0x2a, 0x7e, 0xfb, 0xb1, 0x93, 0x11, 0x8b, 0x5a, 0x9b, 0x92, 0x4b, 0xbd, 0xb7, 0x0b, 0xf9, 0x0c,
	0x4b, 0x45, 0x1f, 0xa5, 0x61, 0x6a, 0x14, 0x7d, 0x7d, 0x93, 0x61, 0x5c, 0xc3, 0xcc, 0x8b, 0x2e,
	0xa2, 0xbb, 0xe8, 0x7e, 0xbe, 0x3a, 0xcf, 0x46, 0x26, 0xd9, 0x8b, 0xc3, 0xaa, 0x17, 0xca, 0x07,
	0x48, 0x07, 0x1f, 0x53, 0xeb, 0xbd, 0x21, 0x3c, 0x83, 0x98, 0x76, 0x3b, 0xda, 0x72, 0x67, 0x73,
	0xa2, 0xdc, 0x24, 0x97, 0x90, 0x3c, 0x11, 0xd3, 0x96, 0xdd, 0x47, 0x99, 0xc2, 0xc2, 0x2f, 0xec,
	0xa9, 0x3c, 0x05, 0xc8, 0xa9, 0xe7, 0x09, 0xcc, 0xbb, 0xc9, 0xc2, 0xd5, 0x5f, 0x04, 0xf0, 0xda,
	0xf6, 0xdc, 0xb4, 0x3d, 0x71, 0x03, 0x33, 0xff, 0x1a, 0x6f, 0x82, 0xa4, 0x41, 0x37, 0x71, 0x3b,
	0xc9, 0xdd, 0xe3, 0x23, 0xcc, 0x21, 0xb6, 0x61, 0xf0, 0x2a, 0x10, 0x8f, 0x42, 0x8b, 0xeb, 0x09,
	0xda, 0x1b, 0x3d, 0xc2, 0x71, 0x4e, 0x8c, 0x97, 0x81, 0x6e, 0xe8, 0x25, 0xc4, 0x21, 0xe4, 0xef,
	0xdf, 0xe3, 0x6e, 0xbb, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x12, 0x87, 0x18, 0xb6, 0xd4, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorldModelClient is the client API for WorldModel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorldModelClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type worldModelClient struct {
	cc *grpc.ClientConn
}

func NewWorldModelClient(cc *grpc.ClientConn) WorldModelClient {
	return &worldModelClient{cc}
}

func (c *worldModelClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/deltav.protos.WorldModel/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldModelClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, "/deltav.protos.WorldModel/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldModelClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/deltav.protos.WorldModel/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorldModelServer is the server API for WorldModel service.
type WorldModelServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterWorldModelServer(s *grpc.Server, srv WorldModelServer) {
	s.RegisterService(&_WorldModel_serviceDesc, srv)
}

func _WorldModel_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldModelServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deltav.protos.WorldModel/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldModelServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldModel_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldModelServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deltav.protos.WorldModel/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldModelServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldModel_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldModelServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deltav.protos.WorldModel/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldModelServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorldModel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deltav.protos.WorldModel",
	HandlerType: (*WorldModelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _WorldModel_Register_Handler,
		},
		{
			MethodName: "Detect",
			Handler:    _WorldModel_Detect_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WorldModel_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worldmodel.proto",
}
