// Code generated by protoc-gen-go. DO NOT EDIT.
// source: position.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Position struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=X,json=x,proto3" json:"X,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=Y,json=y,proto3" json:"Y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=Z,json=z,proto3" json:"Z,omitempty"`
	T                    int64    `protobuf:"varint,4,opt,name=T,json=t,proto3" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_56e266f1a28a7893, []int{0}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Position) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Position) GetT() int64 {
	if m != nil {
		return m.T
	}
	return 0
}

func init() {
	proto.RegisterType((*Position)(nil), "common.Position")
}

func init() { proto.RegisterFile("position.proto", fileDescriptor_56e266f1a28a7893) }

var fileDescriptor_56e266f1a28a7893 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc8, 0x2f, 0xce,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0x53, 0x72, 0xe2, 0xe2, 0x08, 0x80, 0xca, 0x08, 0xf1, 0x70, 0x31, 0x46, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x30, 0x06, 0x31, 0x56, 0x80, 0x78, 0x91, 0x12, 0x4c, 0x10, 0x5e, 0x25, 0x88,
	0x17, 0x25, 0xc1, 0x0c, 0xe1, 0x55, 0x81, 0x78, 0x21, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41,
	0x8c, 0x25, 0x49, 0x6c, 0x60, 0x23, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x14, 0x26,
	0xe8, 0x64, 0x00, 0x00, 0x00,
}
